name: '532-group-30'
channels:
    - conda-forge
    - defaults
dependencies:
    - ipykernel
    - altair-all
    - dash
    - dash-bootstrap-components
    - gunicorn
    - plotly
    - tabulate
    - lxml
    - pandas
    - numpy
    - pip
    - pip:
        - dash-vega-components