name: '532-group-30'
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.12
    - ipykernel
    - altair=5.3.0
    - dash=2.18.2
    - dash-bootstrap-components=1.7.1
    - pandas=2.2.3
    - gunicorn=23.0.0
    - pip
    - pip:
        - dash-vega-components==0.11.0